name: Bug report
description: Create a bug report to help us improve.
labels:
  - bug
body:
  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: behaviour
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happens.
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the reported behaviour.
  - type: textarea
    id: luciconfig
    attributes:
      label: HomeProxy configuration
      description: |
        The HomeProxy configuration file where the error occurred (use command below).
        ```cat /etc/config/homeproxy```
    validations:
      required: true
  - type: textarea
    id: coreconfig
    attributes:
      label: sing-box configuration
      description: |
        The sing-box configuration file where the error occurred (use command below).
        For client: ```cat /var/run/homeproxy/sing-box-c.json```
        For server: ```cat /var/run/homeproxy/sing-box-s.json```
    validations:
      required: true
  - type: textarea
    id: lucilog
    attributes:
      label: HomeProxy log
      description: |
        The HomeProxy log file where the error occurred (use command below).
        ```cat /var/run/homeproxy/homeproxy.log```
    validations:
      required: false
  - type: textarea
    id: corelog
    attributes:
      label: sing-box log
      description: |
        The sing-box log file where the error occurred (use command below).
        For client: ```cat /var/run/homeproxy/sing-box-c.log```
        For server: ```cat /var/run/homeproxy/sing-box-s.log```
    validations:
      required: true

  - type: textarea
    id: syslog
    attributes:
      label: System log
      description: |
        Paste system log if the daemon cannot start (use command below).
        ```logread -e sing-box```

  - type: input
    id: osrelease
    attributes:
      label: OpenWrt/ImmortalWrt release
      description: |
        The OpenWrt/ImmortalWrt release or commit hash where this bug occurs (use command below).
        ```. /etc/openwrt_release && echo $DISTRIB_RELEASE $DISTRIB_REVISION```
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device
      description: |
        The device exhibiting this bug (if unsure, use command below).
        ```cat /tmp/sysinfo/model```
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Add any additional info you think might be helfpul.
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: Please check the following before submitting the issue.
      options:
        - label: I confirm that the HomeProxy I installed is from official source, like GitHub artifacts or official ImmortalWrt opkg feeds.
          required: true
        - label: I confirm that the Homeproxy I installed does not contain Clash mode support.
          required: true
        - label: I confirm that the version of OpenWrt/ImmortalWrt I installed is >= 24.10.
          required: true
        - label: I confirm that I have installed the latest version of HomeProxy and sing-box.
          required: true
        - label: I confirm that I have read the sing-box documentation, understand the meaning of all the configuration items I added.
          required: true
        - label: I confirm that I have not mixed iptables and nftables rules.
          required: true
        - label: I confirm that I have not modified system DNS settings, or enabled any other DNS servers like MosDNS and SmartDNS.
          required: true
        - label: I confirm that I have cleared the browser cache.
          required: true
        - label: I confirm that I have selected all terms **blindly**.
          required: false
