#!/bin/sh

[ -f "/www/luci-static/resources/icons/loading.gif" ] && \
	sed -i "s,/loading.svg,/loading.gif,g" "/www/luci-static/resources/view/canto/status.js"

uci -q batch <<-EOF >"/dev/null"
	delete firewall.canto_pre

	delete firewall.canto_forward
	set firewall.canto_forward=include
	set firewall.canto_forward.type=nftables
	set firewall.canto_forward.path="/var/run/canto/fw4_forward.nft"
	set firewall.canto_forward.position="chain-pre"
	set firewall.canto_forward.chain="forward"

	delete firewall.canto_input
	set firewall.canto_input=include
	set firewall.canto_input.type=nftables
	set firewall.canto_input.path="/var/run/canto/fw4_input.nft"
	set firewall.canto_input.position="chain-pre"
	set firewall.canto_input.chain="input"

	delete firewall.canto_post
	set firewall.canto_post=include
	set firewall.canto_post.type=nftables
	set firewall.canto_post.path="/var/run/canto/fw4_post.nft"
	set firewall.canto_post.position="table-post"
	commit firewall
EOF

exit 0
