#!/bin/sh

if [ -e "$(command -v fw4)" ]; then
	uci -q batch <<-EOF >"/dev/null"
		delete firewall.homeproxy
		set firewall.homeproxy=include
		set firewall.homeproxy.type=nftables
		set firewall.homeproxy.path="/var/run/homeproxy/fw4.nft"
		set firewall.homeproxy.position="table-pre"
		commit firewall
	EOF
else
	uci -q batch <<-EOF >"/dev/null"
		delete firewall.homeproxy
		set firewall.homeproxy=include
		set firewall.homeproxy.type=script
		set firewall.homeproxy.path="/var/run/homeproxy/homeproxy.include"
		set firewall.homeproxy.reload=1
		commit firewall
	EOF
fi

rm -f /tmp/luci-indexcache
exit 0
