#!/bin/sh

uci -q batch <<-EOF >"/dev/null"
	delete firewall.homeproxy_pre

	delete firewall.homeproxy_pre_input
	set firewall.homeproxy_pre_input=include
	set firewall.homeproxy_pre_input.type=nftables
	set firewall.homeproxy_pre_input.path="/var/run/homeproxy/fw4_pre_input.nft"
	set firewall.homeproxy_pre_input.position="chain-pre"
	set firewall.homeproxy_pre_input.chain="input"

	delete firewall.homeproxy_pre_forward
	set firewall.homeproxy_pre_forward=include
	set firewall.homeproxy_pre_forward.type=nftables
	set firewall.homeproxy_pre_forward.path="/var/run/homeproxy/fw4_pre_forward.nft"
	set firewall.homeproxy_pre_forward.position="chain-pre"
	set firewall.homeproxy_pre_forward.chain="forward"

	delete firewall.homeproxy_post
	set firewall.homeproxy_post=include
	set firewall.homeproxy_post.type=nftables
	set firewall.homeproxy_post.path="/var/run/homeproxy/fw4_post.nft"
	set firewall.homeproxy_post.position="table-post"
	commit firewall
EOF

exit 0
