#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2022-2023 ImmortalWrt.org

USE_PROCD=1

START=99
STOP=10

CONF="homeproxy"
PROG="/usr/bin/hiddify-core"

HP_DIR="/etc/homeproxy"
RUN_DIR="/var/run/homeproxy"
LOG_PATH="$RUN_DIR/homeproxy.log"

# we don't know which is the default server, just take the first one
DNSMASQ_UCI_CONFIG="$(uci -q show "dhcp.@dnsmasq[0]" | awk 'NR==1 {split($0, conf, /[.=]/); print conf[2]}')"
if [ -f "/tmp/etc/dnsmasq.conf.$DNSMASQ_UCI_CONFIG" ]; then
	DNSMASQ_DIR="$(awk -F '=' '/^conf-dir=/ {print $2}' "/tmp/etc/dnsmasq.conf.$DNSMASQ_UCI_CONFIG")/dnsmasq-homeproxy.d"
else
	DNSMASQ_DIR="/tmp/dnsmasq.d/dnsmasq-homeproxy.d"
fi

log() {
	echo -e "$(date "+%Y-%m-%d %H:%M:%S") [DAEMON] $*" >> "$LOG_PATH"
}

start_service() {
	config_load "$CONF"

	local routing_mode proxy_mode
	config_get routing_mode "config" "routing_mode" "bypass_mainland_china"
	config_get proxy_mode "config" "proxy_mode" "redirect_tproxy"

	mkdir -p "$RUN_DIR"

	# Generate or copy client config
	if [ "$routing_mode" = "custom_json" ]; then
		if [ -e "$HP_DIR/hiddify-c.json" ]; then
			cp "$HP_DIR/hiddify-c.json" "$RUN_DIR/hiddify-c.json"
		elif [ ! -e "$RUN_DIR/hiddify-c.json" ]; then
			log "Error: client config not found. Place your config at $HP_DIR/hiddify-c.json"
			return 1
		fi
	else
		rm -f "$RUN_DIR/hiddify-c.json"
		ucode "$HP_DIR/scripts/generate_client.uc"
		if [ ! -e "$RUN_DIR/hiddify-c.json" ]; then
			log "Error: failed to generate client config."
			return 1
		fi
	fi

	# DNSMasq rules
	local ipv6_support dns_port
	config_get_bool ipv6_support "config" "ipv6_support" "0"
	config_get dns_port "infra" "dns_port" "5333"
	mkdir -p "$DNSMASQ_DIR"
	echo -e "conf-dir=$DNSMASQ_DIR" > "$DNSMASQ_DIR/../dnsmasq-homeproxy.conf"
	case "$routing_mode" in
	"bypass_mainland_china"|"custom"|"custom_json"|"global")
		cat <<-EOF >> "$DNSMASQ_DIR/redirect-dns.conf"
			no-poll
			no-resolv
			server=127.0.0.1#$dns_port
		EOF
		;;
	"gfwlist")
		local gfw_nftset_v6
		[ "$ipv6_support" -eq "0" ] || gfw_nftset_v6=",6#inet#fw4#homeproxy_gfw_list_v6"
		sed -r -e "s/(.*)/server=\/\1\/127.0.0.1#$dns_port\nnftset=\/\1\\/4#inet#fw4#homeproxy_gfw_list_v4$gfw_nftset_v6/g" \
			"$HP_DIR/resources/gfw_list.txt" > "$DNSMASQ_DIR/gfw_list.conf"
		;;
	"proxy_mainland_china")
		sed -r -e "s/(.*)/server=\/\1\/127.0.0.1#$dns_port/g" \
			"$HP_DIR/resources/china_list.txt" > "$DNSMASQ_DIR/china_list.conf"
		;;
	esac
	/etc/init.d/dnsmasq restart >"/dev/null" 2>&1

	# Setup tproxy routing table
	local table_mark tproxy_mark
	config_get table_mark "infra" "table_mark" "100"
	config_get tproxy_mark "infra" "tproxy_mark" "101"

	ip rule add fwmark "$tproxy_mark" table "$table_mark"
	ip route add local 0.0.0.0/0 dev lo table "$table_mark"

	if [ "$ipv6_support" -eq "1" ]; then
		ip -6 rule add fwmark "$tproxy_mark" table "$table_mark"
		ip -6 route add local ::/0 dev lo table "$table_mark"
	fi

	# hiddify-core (client)
	procd_open_instance "hiddify-c"

	procd_set_param command "$PROG"
	procd_append_param command srun --config "$RUN_DIR/hiddify-c.json"

	# QUIC-GO GSO is broken on kernel 6.6 currently
	uname -r | grep -Eq "^6\.6" && procd_set_param env "QUIC_GO_DISABLE_GSO"="true"

	procd_set_param limits core="unlimited"
	procd_set_param limits nofile="1000000 1000000"
	procd_set_param stderr 1
	procd_set_param respawn

	procd_close_instance

	# log-cleaner
	procd_open_instance "log-cleaner"
	procd_set_param command "$HP_DIR/scripts/clean_log.sh"
	procd_set_param respawn
	procd_close_instance

	echo > "$RUN_DIR/hiddify-c.log"

	# Setup firewall
	ucode "$HP_DIR/scripts/firewall_pre.uc"
	utpl -S "$HP_DIR/scripts/firewall_post.ut" > "$RUN_DIR/fw4_post.nft"
	fw4 reload >"/dev/null" 2>&1

	log "hiddify-core started."
}

stop_service() {
	sed -i "/#${CONF}_autosetup/d" "/etc/crontabs/root" 2>"/dev/null"
	/etc/init.d/cron restart >"/dev/null" 2>&1

	# Load config
	config_load "$CONF"
	local table_mark tproxy_mark tun_name
	config_get table_mark "infra" "table_mark" "100"
	config_get tproxy_mark "infra" "tproxy_mark" "101"
	config_get tun_name "infra" "tun_name" "singtun0"

	# Tproxy
	ip rule del fwmark "$tproxy_mark" table "$table_mark" 2>"/dev/null"
	ip route del local 0.0.0.0/0 dev lo table "$table_mark" 2>"/dev/null"
	ip -6 rule del fwmark "$tproxy_mark" table "$table_mark" 2>"/dev/null"
	ip -6 route del local ::/0 dev lo table "$table_mark" 2>"/dev/null"

	# Nftables rules
	for i in "homeproxy_dstnat_redir" "homeproxy_output_redir" \
		 "homeproxy_redirect" "homeproxy_redirect_proxy" \
		 "homeproxy_redirect_proxy_port" "homeproxy_redirect_lanac" \
		 "homeproxy_mangle_prerouting" "homeproxy_mangle_output" \
		 "homeproxy_mangle_tproxy" "homeproxy_mangle_tproxy_port" \
		 "homeproxy_mangle_tproxy_lanac" "homeproxy_mangle_mark" \
		 "homeproxy_mangle_tun" "homeproxy_mangle_tun_mark"; do
		nft flush chain inet fw4 "$i"
		nft delete chain inet fw4 "$i"
	done 2>"/dev/null"
	for i in "homeproxy_local_addr_v4" "homeproxy_local_addr_v6" \
		 "homeproxy_gfw_list_v4" "homeproxy_gfw_list_v6" \
		 "homeproxy_mainland_addr_v4" "homeproxy_mainland_addr_v6" \
		 "homeproxy_wan_proxy_addr_v4" "homeproxy_wan_proxy_addr_v6" \
		 "homeproxy_wan_direct_addr_v4" "homeproxy_wan_direct_addr_v6" \
		 "homeproxy_routing_port"; do
		nft flush set inet fw4 "$i"
		nft delete set inet fw4 "$i"
	done 2>"/dev/null"
	echo 2>"/dev/null" > "$RUN_DIR/fw4_forward.nft"
	echo 2>"/dev/null" > "$RUN_DIR/fw4_input.nft"
	echo 2>"/dev/null" > "$RUN_DIR/fw4_post.nft"
	fw4 reload >"/dev/null" 2>&1

	# Remove DNS hijack
	rm -rf "$DNSMASQ_DIR/../dnsmasq-homeproxy.conf" "$DNSMASQ_DIR"
	/etc/init.d/dnsmasq restart >"/dev/null" 2>&1

	# Only remove the log; hiddify-c.json is manually placed by the user
	rm -f "$RUN_DIR/hiddify-c.log"

	log "Service stopped."
}

service_stopped() {
	config_load "$CONF"
	local tun_name
	config_get tun_name "infra" "tun_name" "singtun0"

	ip link set "$tun_name" down 2>"/dev/null"
	ip tuntap del mode tun name "$tun_name" 2>"/dev/null"
}

reload_service() {
	log "Reloading service..."

	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "$CONF"
	procd_add_interface_trigger "interface.*.up" wan /etc/init.d/$CONF reload
}
